// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using PersonDBExample.Models;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PersonDBExample.Models;

namespace PersonDBExample.Data
{
    public partial class PersonexampledbContext : DbContext
    {
        public PersonexampledbContext()
        {
        }

        public PersonexampledbContext(DbContextOptions<PersonexampledbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Person> Person { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=LAPTOP-EJINSC9P\\SQLEXPRESS;Initial Catalog=PersonExampleDB;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>(entity =>
            {
                entity.Property(e => e.EyeColor).IsFixedLength();

                entity.Property(e => e.Sex).IsFixedLength();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}